export const SET_SCROLL = 'SET_SCROLL'

export const SET_PROD_NAME = 'SET_PROD_NAME'
export const SET_PROD_PRICE = 'SET_PROD_PRICE'
export const COMMIT_PRODUCT = 'COMMIT_PRODUCT'

export const INCREMENT_NUM_A = 'INCREMENT_NUM_A'
export const INCREMENT_NUM_B = 'INCREMENT_NUM_B'
export const DECREMENT_NUM_A = 'DECREMENT_NUM_A'
export const DECREMENT_NUM_B = 'DECREMENT_NUM_B'
